services:
  mongo:
    image: mongo:8.3.11
    container_name: neAvito-mongo
    restart: unless-stopped

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_DATABASE: neAvito

    volumes:
      - mongo_data:/data

volumes:
  mongo_data:
